language: objective-c
osx_image: xcode7.3

script:
  - xcodebuild -workspace Releans.xcworkspace -scheme Releans ONLY_ACTIVE_ARCH=NO
  - xcodebuild -workspace Releans.xcworkspace -scheme Releans -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6s,OS=9.3' test